### ISSUE TITLE
kernel crash when trying python3 notebook

### ISSUE THREAD

**Issue by sebgoa** [nbgallery/jupyter-docker#11]
I am a newbie with jupyter. Looking for a small image it seems that you have really optimized things well.

Except that I can't see to start a python3 nb, the kernel crashes and can't restart.

**Comment by somedave** [comment]
Hey sorry about this!  One of the ways we keep our image so small is we dynamically install kernels (to include the Python 3 kernel) using Alpine packages that we've created and hosted.  We're currently in between hosting providers which is why your instance is unable get to and install the Py3 kernel.  I hope to have this fixed at some point next week and I'll follow up on this ticket to let you know when it's working.

**Comment by sebgoa** [comment]
cool, thanks for making a small image, I tested an official one from jupiter and it was 2.2GB...:(

**Comment by somedave** [comment]
Hey sorry for the delay on this - if you pull our latest image from docker hub you should be good to go.

**Comment by sebgoa** [comment]
thanks I will give it a shot.
